language: python
dist: xenial

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8

env:
  - CC=gcc-8

before_install:
  - $CC --version

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install

script:
  - poetry run make -C tests
  - poetry run make -C examples/basic

jobs:
  include:
    - python: 3.7

    - stage: publish
      python: 3.7
      if: tag IS present
      script:
        - poetry build
        - poetry publish --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD"
